export default {
    dailyUsage: [
        { skill: "Typescript", id: crypto.randomUUID() },
        { skill: "Emotion", id: crypto.randomUUID() },
        { skill: "React", id: crypto.randomUUID() },
        { skill: "Next.js", id: crypto.randomUUID() },
        { skill: "Redux Toolkit", id: crypto.randomUUID() },
        { skill: "Storybook", id: crypto.randomUUID() },
        { skill: "React Testing Library", id: crypto.randomUUID() },
        { skill: "Jest", id: crypto.randomUUID() },
        { skill: "Java", id: crypto.randomUUID() },
        { skill: "Spring Boot", id: crypto.randomUUID() },
        { skill: "Ruby", id: crypto.randomUUID() },
        { skill: "Ruby on Rails", id: crypto.randomUUID() },
        { skill: "RSpec", id: crypto.randomUUID() },
        { skill: "Capybara", id: crypto.randomUUID() },
        { skill: "PostgreSQL", id: crypto.randomUUID() },
        { skill: "AWS", id: crypto.randomUUID() },
        { skill: "GitLab", id: crypto.randomUUID() },
        { skill: "Google", id: crypto.randomUUID() },
        { skill: "Figma", id: crypto.randomUUID() },
        { skill: "DataDog", id: crypto.randomUUID() },
        { skill: "Postman", id: crypto.randomUUID() },
        { skill: "Plausible", id: crypto.randomUUID() },
        { skill: "Notion", id: crypto.randomUUID() },
    ],
    workedWith: [
        { skill: "styled-components", id: crypto.randomUUID() },
        { skill: "SCSS/SASS", id: crypto.randomUUID() },
        { skill: "jQuery", id: crypto.randomUUID() },
        { skill: "RTK Query", id: crypto.randomUUID() },
        { skill: "Python", id: crypto.randomUUID() },
        { skill: "Flask", id: crypto.randomUUID() },
        { skill: "FastAPI", id: crypto.randomUUID() },
        { skill: "Express.js", id: crypto.randomUUID() },
        { skill: "MongoDB", id: crypto.randomUUID() },
        { skill: "SQLite", id: crypto.randomUUID() },
        { skill: "SQL", id: crypto.randomUUID() },
        { skill: "Terraform", id: crypto.randomUUID() },
        { skill: "Terragrunt", id: crypto.randomUUID() },
        { skill: "Vercel", id: crypto.randomUUID() },
        { skill: "Heroku", id: crypto.randomUUID() },
        { skill: "Auth0", id: crypto.randomUUID() },
    ],
    experimentedWith: [
        { skill: "Django", id: crypto.randomUUID() },
        { skill: "RabbitMQ", id: crypto.randomUUID() },
        { skill: "Celery", id: crypto.randomUUID() },
        { skill: "Rust", id: crypto.randomUUID() },
        { skill: "Go", id: crypto.randomUUID() },
        { skill: "Docker", id: crypto.randomUUID() },
        { skill: "Nx", id: crypto.randomUUID() },
    ],
};
