export default {
    components: {
        copyright: {
            footer: "copyright-footer",
            text: "copyright-text",
        },
        externalLink: {
            image: "external-link-image",
        },
        nav: {
            mobileNav: {},
            navbar: {
                container: "navbar-container",
                logo: "navbar-logo",
                navSection: "navbar-nav-section",
                nav: "navbar-nav",
                navList: "navbar-nav-list",
                navItem: "navbar-nav-item",
                navLink: "navbar-nav-link",
                navButton: "navbar-nav-button",
                navButtonImage: "navbar-nav-button-image",
            },
        },
        projectCard: {},
        socials: {},
    },
    pages: {
        about: {},
        contact: {
            contactInfoContainer: "contact-page-contact-info-container",
            contactInfoHeader: "contact-page-contact-info-header",
            container: "contact-page-container",
            copyContactInfoButton: "contact-page-copy-contact-info-button",
            externalLink: "contact-page-external-link",
            externalLinkContainer: "contact-page-external-link-container",
            header: "contact-page-header",
            headerFirstWord: "contact-page-header-first-word",
            headerSecondWord: "contact-page-header-second-word",
            image: "contact-page-image",
            imageContainer: "contact-page-image-container",
            linksHeader: "contact-page-links-header",
        },
        error: {},
        experience: {},
        globalError: {},
        landing: {
            container: "landing-page-container",
            firstName: "landing-page-first-name",
            jobTitle: "landing-page-job-title",
            lastName: "landing-page-last-name",
            name: "landing-page-name",
        },
        notFound: {},
        uses: {},
        wpAdmin: {},
    },
};
