export default {
    components: {
        copyright: {
            footer: "copyright-footer",
            text: "copyright-text",
        },
        externalLink: {
            image: "external-link-image",
        },
        nav: {
            mobileNav: {
                container: "mobile-nav-container",
                closingButton: "mobile-nav-closing-button",
                logo: "mobile-nav-logo",
                nav: "mobile-nav-nav",
                navList: "mobile-nav-nav-list",
                navItem: "mobile-nav-nav-item",
                navLink: "mobile-nav-nav-link",
            },
            navbar: {
                container: "navbar-container",
                logo: "navbar-logo",
                navSection: "navbar-nav-section",
                nav: "navbar-nav",
                navList: "navbar-nav-list",
                navItem: "navbar-nav-item",
                navLink: "navbar-nav-link",
                navButton: "navbar-nav-button",
                navButtonImage: "navbar-nav-button-image",
            },
        },
        projectCard: {},
        socials: {
            container: "socials-container",
            text: "socials-text",
            divider: "socials-divider",
            link: "socials-link",
            icon: "socials-icon",
        },
    },
    pages: {
        about: {},
        contact: {
            contactInfoContainer: "contact-page-contact-info-container",
            contactInfoHeader: "contact-page-contact-info-header",
            container: "contact-page-container",
            copyContactInfoButton: "contact-page-copy-contact-info-button",
            externalLink: "contact-page-external-link",
            externalLinkContainer: "contact-page-external-link-container",
            header: "contact-page-header",
            headerFirstWord: "contact-page-header-first-word",
            headerSecondWord: "contact-page-header-second-word",
            image: "contact-page-image",
            imageContainer: "contact-page-image-container",
            linksHeader: "contact-page-links-header",
        },
        experience: {},
        landing: {
            container: "landing-page-container",
            firstName: "landing-page-first-name",
            jobTitle: "landing-page-job-title",
            lastName: "landing-page-last-name",
            name: "landing-page-name",
        },
        notFound: {
            container: "not-found-page-container",
            header: "not-found-page-header",
            image: "not-found-page-image",
            link: "not-found-page-link",
            text: "not-found-page-text",
        },
        uses: {
            container: "uses-page-container",
            pageHeader: "uses-page-header",
            description: "uses-page-description",
            descriptionExternalLink: "uses-page-description-external-link",
            softwareSectionHeader: "uses-page-software-section-header",
            softwareSectionHeaderSpan: "uses-page-software-section-header-span",
            softwareList: "uses-page-software-list",
            softwareListItem: "uses-page-software-list-item",
            softwareListItemParagraph: "uses-page-software-list-item-paragraph",
            softwareListItemExternalLink: "uses-page-software-list-item-external-link",
            hardwareList: "uses-page-hardware-list",
            hardwareSectionHeader: "uses-page-hardware-section-header",
            hardwareListItem: "uses-page-hardware-list-item",
            hardwareListItemParagraph: "uses-page-hardware-list-item-paragraph",
        },
        wpAdmin: {
            container: "wp-admin-page-container",
            image: "wp-admin-page-image",
        },
    },
};
