const testingIds = {
    components: {
        copyright: {
            footer: "copyright-footer",
            text: "copyright-text",
        },
        externalLink: {
            image: "external-link-image",
        },
        mobileExternalNavLink: {
            image: "mobile-external-nav-link-image",
        },
        nav: {
            mobileNav: {
                closingButton: "mobile-nav-closing-button",
                container: "mobile-nav-container",
                logo: "mobile-nav-logo",
                nav: "mobile-nav-nav",
                navItem: "mobile-nav-nav-item",
                navLink: "mobile-nav-nav-link",
                navList: "mobile-nav-nav-list",
            },
            navbar: {
                container: "navbar-container",
                logo: "navbar-logo",
                nav: "navbar-nav",
                navButton: "navbar-nav-button",
                navButtonImage: "navbar-nav-button-image",
                navItem: "navbar-nav-item",
                navLink: "navbar-nav-link",
                navList: "navbar-nav-list",
                navSection: "navbar-nav-section",
            },
        },
        projectCard: {
            codeLink: "project-card-code-link",
            container: "project-card-container",
            description: "project-card-description",
            headerSection: "project-card-header-section",
            image: "project-card-image",
            imageSection: "project-card-image-section",
            jobTitle: "project-card-job-title",
            linkSection: "project-card-link-section",
            liveLink: "project-card-live-link",
            name: "project-card-name",
            position: "project-card-position",
            textSection: "project-card-text-section",
        },
        socials: {
            container: "socials-container",
            divider: "socials-divider",
            icon: "socials-icon",
            link: "socials-link",
            text: "socials-text",
        },
        tooltip: {
            container: "tooltip-container",
            text: "tooltip-text",
        },
    },
    pages: {
        about: {
            container: "about-page-container",
            content: "about-page-content",
            greetingHeader: "about-page-greeting-header",
            greetingText: "about-page-greeting-text",
            header: "about-page-header",
            headerSpan: "about-page-header-span",
            image: "about-page-image",
            imageContainer: "about-page-image-container",
            skillList: "about-page-skill-list",
            skillListItem: "about-page-skill-list-item",
            skillListItemText: "about-page-skill-list-item-text",
            skillsHeader: "about-page-skills-header",
            skillUsageHeader: "about-page-skill-usage-header",
            textContainer: "about-page-text-container",
        },
        contact: {
            contactInfoContainer: "contact-page-contact-info-container",
            contactInfoHeader: "contact-page-contact-info-header",
            container: "contact-page-container",
            copyContactInfoButton: "contact-page-copy-contact-info-button",
            externalLink: "contact-page-external-link",
            externalLinkContainer: "contact-page-external-link-container",
            header: "contact-page-header",
            headerFirstWord: "contact-page-header-first-word",
            headerSecondWord: "contact-page-header-second-word",
            image: "contact-page-image",
            imageContainer: "contact-page-image-container",
            linksHeader: "contact-page-links-header",
        },
        experience: {
            container: "experience-page-container",
            header: "experience-page-header",
        },
        landing: {
            container: "landing-page-container",
            firstName: "landing-page-first-name",
            jobTitle: "landing-page-job-title",
            lastName: "landing-page-last-name",
            name: "landing-page-name",
        },
        notFound: {
            container: "not-found-page-container",
            header: "not-found-page-header",
            image: "not-found-page-image",
            link: "not-found-page-link",
            text: "not-found-page-text",
        },
        uses: {
            container: "uses-page-container",
            description: "uses-page-description",
            descriptionExternalLink: "uses-page-description-external-link",
            hardwareList: "uses-page-hardware-list",
            hardwareListItem: "uses-page-hardware-list-item",
            hardwareListItemParagraph: "uses-page-hardware-list-item-paragraph",
            hardwareSectionHeader: "uses-page-hardware-section-header",
            pageHeader: "uses-page-header",
            softwareList: "uses-page-software-list",
            softwareListItem: "uses-page-software-list-item",
            softwareListItemExternalLink: "uses-page-software-list-item-external-link",
            softwareListItemParagraph: "uses-page-software-list-item-paragraph",
            softwareSectionHeader: "uses-page-software-section-header",
            softwareSectionHeaderSpan: "uses-page-software-section-header-span",
        },
        wpAdmin: {
            container: "wp-admin-page-container",
            image: "wp-admin-page-image",
        },
    },
};

export default testingIds;
